FROM tomcat:10-jdk17-temurin

ENV CATALINA_HOME=/usr/local/tomcat

# Remove default ROOT app
RUN rm -rf $CATALINA_HOME/webapps/ROOT

# Deploy your WAR
COPY target/spreg.war $CATALINA_HOME/webapps/ROOT.war

# EXPOSE Tomcat port
EXPOSE 8080

# Run as non-root user (optional, recommended)
USER 1000

# Start Tomcat
CMD ["catalina.sh", "run"]
