#
# spreg idp tools install playbook
#

- hosts: "{{ target }}"
  serial: 1
  max_fail_percentage: 10

  tasks:
  - name: create conf yml file
    local_action: pyconf_to_yml spreg_idp {{ cluster_type }}

  - include_vars: "conf.yml"

  - name: copy programs  and configs
    copy: "src={{ item.src }} dest={{ item.dest }} group=iam-dev mode=664 "
    with_items:
       - { src: '../spreg_update.py', dest: '{{ idp_base }}/bin/spreg_update.py' }
       - { src: '../spreg_update.conf.{{ cluster_type }}', dest: '{{ idp_base }}/bin/spreg_update.conf' }
       - { src: '../filter_scan.py', dest: '{{ idp_base }}/bin/filter_scan.py' }
       - { src: '../filter_scan.conf.{{ cluster_type }}', dest: '{{ idp_base }}/bin/filter_scan.conf' }
    when: item.src != ""

 
