#
# spreg install playbook
#

- hosts: "{{ target }}"
  serial: 1
  max_fail_percentage: 10

  tasks:
  - include_vars: "properties.yml"

  # update http and https config
  - include: "tasks/apache_config.yml file=https"
  - include: "tasks/apache_config.yml file=http"

  # copy js files
  - name: copy js files
    copy: "src=../src/main/webapp/sp.js dest=/www/js/sp.js group=pubcookie mode=664"
    notify:
      - restart apache

  # update certs and keys
  - name: copy crt
    copy: "src={{ local_crt_file }} dest={{ crt_file }} group=pubcookie mode=660 "
    when: local_crt_file is defined
  - name: copy key
    copy: "src={{ local_key_file }} dest={{ key_file }} group=pubcookie mode=660"
    when: local_key_file is defined
  - name: copy ca
    copy: "src={{ local_ca_file }} dest={{ ca_file }} group=pubcookie mode=664"
    when: local_ca_file is defined

  # update the spreg.war file
  - name: copy war
    copy: "src=../target/spreg.war dest=/data/webapps/spreg.war group=pubcookie mode=664"
    notify:
      - restart tomcat

  handlers:
    - include: "tasks/iam_handlers.yml"

