#
# spreg install playbook
#

- hosts: "{{ target }}"
  serial: 1
  max_fail_percentage: 10

  tasks:
  - include_vars: "local_vars.yml"

  - name: create properties yml file
    local_action: property_to_yml spreg {{ cluster_type }}

  - include_vars: "properties.yml"

  # copy spreg properties file
  # change restarts tomcat
  - name: copy properties file
    copy: "src=../spreg.properties.{{ cluster_type }}  dest={{ spreg_root }}/spreg.properties group=iam-dev mode=664"
    notify: restart tomcat
 
  # configure tomcat startup properties
  # change restarts tomcat
  - name: tomcat startup params
    daemon_config: "service=tomcat key=spreg.properties value=file:{{ spreg_root }}/spreg.properties"
    notify: restart tomcat

  # update http and https config
  # change restarts apache
  - include: "tasks/apache_config.yml file=https prod=spreg"
  - include: "tasks/apache_config.yml file=http prod=spreg"

  # copy js files
  - name: copy js files
    copy: "src=../src/main/webapp/sp.js dest=/www/js/sp.js group=iam-dev mode=664"
    when: non_standard_apache is not defined

  # copy css files
  - name: copy css files
    copy: "src=../src/main/webapp/sp.css dest=/www/css/sp.css group=iam-dev mode=664"
    when: non_standard_apache is not defined

  # update certs and keys (used by spreg)
  # change restarts tomcat
  - name: copy certs and keys
    copy: "src={{ item.src }} dest={{ item.dest }} group=iam-dev mode=664 "
    with_items:
       - { src: '{{local_webclient_certFile}}', dest: '{{spreg_webclient_certFile}}' }
       - { src: '{{local_webclient_keyFile}}', dest: '{{spreg_webclient_keyFile}}' }
       - { src: '{{local_webclient_caFile}}', dest: '{{spreg_webclient_caFile}}' }
    when: have_local_certs is defined and item.src != ""
    notify: restart tomcat

  # copy the attributes data file
  # until this is in the dataabse 
  - name: copy attribute data
    copy: "src=../attribute.xml dest={{ spreg_root }}/attribute.xml group=iam-dev mode=664"
    notify: restart tomcat

  # update the spreg.war file
  - name: copy war
    copy: "src=../target/spreg.war dest=/data/webapps/spreg.war group=iam-dev mode=664"
    notify: restart tomcat

  # run any handlers 
  - meta: flush_handlers

  # always run the test
  - name: run service tests
    local_action:  "command wget  -O /dev/null
           --certificate={{ local_webclient_certFile }}
           --private-key={{ local_webclient_keyFile }}
           --ca-certificate={{ local_webclient_caFile }}
           --no-check-certificate
            'https://{{inventory_hostname}}/spreg/ws/metadata?mdid=UW&id=https://iam-ws.u.washington.edu/'"
    register: wget_result
    changed_when: "wget_result.rc != 0"

  # idle loadr if test fails
  - name: idle loadr if test fail
    command: /usr/bin/nohup /data/local/bin/ansible_command loadr idle
    when: "wget_result.rc != 0"
      
  # fail if test fails
  - name: fail if test fail
    fail: msg="API service test fails after install"
    when: "wget_result.rc != 0"
      

  # handlers mostly standard from iam-ansible

  handlers:
    - include: "tasks/iam_handlers.yml"


